#!/usr/bin/env node
// Break-out box BROWSER check: the free grid, the shape thumbnails and the trigger fold.
// All three are live-DOM behaviour, so like tools/foldcycle-check.js this one needs a
// browser -- which is why it is NOT named *probe.js: /deploy runs `node tools/*probe.js`
// over the directory.
//
//   node tools/breakout-check.js <outdir> [dev-index.html]
//
// then run the printed msedge command. Every line is PASS/FAIL on stderr via CONSOLE.
//
// The traps this had to work around, all of them documented in CLAUDE.md and all of them
// hit here: the layer rows are a fixed pool with the spares HIDDEN (so offsetParent, not
// querySelectorAll length); a control only has a break-out box once it is POPPED, which
// means clicking the real launcher rather than un-hiding anything; and the panel has to
// stay open, which now also holds the auto-cycle timer so nothing swaps the scene mid-run.
//
// No backtick anywhere in the injected source, and it is assembled from arrays joined by an
// explicit newline rather than template literals.
const fs = require("fs");
const path = require("path");
const NL = String.fromCharCode(10);
const Q = String.fromCharCode(39);

const outDir = process.argv[2];
const appFile = process.argv[3] || "dev-index.html";
if (!outDir) { console.error("usage: node tools/breakout-check.js <outdir> [dev-index.html]"); process.exit(2); }
fs.mkdirSync(outDir, { recursive: true });
const app = fs.readFileSync(appFile, "utf8");

const SEED = [
  "(function(){",
  "  try {",
  "    localStorage.clear();",
  "    localStorage.setItem(\"burnTheWeb.v1\", JSON.stringify({ panelOpen: true, cycle: false, tdur: [0, 0] }));",
  "    localStorage.setItem(\"burnTheWeb.tutorial.v1\", \"1\");",
  "    localStorage.setItem(\"burnTheWeb.credits.v1\", \"off\");",
  "    localStorage.setItem(\"burnTheWeb.sync.v1\", JSON.stringify({ shows: 9, done: true }));",
  "  } catch (e) {}",
  "  window.__errs = 0;",
  "  var ce = console.error;",
  "  console.error = function(){ window.__errs++; ce.apply(console, arguments); };",
  "  window.addEventListener(\"error\", function(){ window.__errs++; });",
  "})();",
].join(NL);

const ASSERT = [
  "(function(){",
  "  var fails = 0;",
  "  function ok(name, cond, extra){",
  "    // NAME FIRST. Getting this pair the wrong way round makes the assertion pass",
  "    // unconditionally -- the name is a non-empty string, so it is always truthy as a",
  "    // condition -- and it happened four times in one sitting here, hiding a real miss",
  "    // behind a green line reading \"PASS true\". So the signature enforces itself.",
  "    if (typeof name !== \"string\") {",
  "      console.log(\"FAIL  ok() called with its arguments swapped: \" + name + \" / \" + cond);",
  "      fails++; return;",
  "    }",
  "    console.log((cond ? \"PASS  \" : \"FAIL  \") + name + (extra ? \"  [\" + extra + \"]\" : \"\"));",
  "    if (!cond) fails++;",
  "  }",
  "  function vis(list){ return [].slice.call(list).filter(function(n){ return n.offsetParent !== null; }); }",
  "  function pt(type, x, y){ return new PointerEvent(type, { clientX: x, clientY: y, bubbles: true, button: 0, pointerId: 1 }); }",
  "",
  "  setTimeout(function(){",
  "    ok(\"the app started clean\", window.__errs === 0, window.__errs + \" console errors\");",
  "    // A frame count is NOT a startup-health check. Measured against the build that linked",
  "    // a 64-second shader at boot: this read 17 frames at 45 fps and passed, because the",
  "    // harness's virtual clock simply waits through a synchronous stall. The only thing",
  "    // that sees a hang is WALL time -- which is what the generator prints below, and what",
  "    // the startup-time gate in tools/startup-check.sh asserts.",
  "    // A shape family: put the one visible layer on Polygon, then unfold its block so the",
  "    // launcher rows are reachable.",
  "    var row = vis(document.querySelectorAll(\"select.lyr-name\"))[0];",
  "    var opt = [].slice.call(row.options).filter(function(o){ return o.textContent.trim() === \"Concentric rings\"; })[0];",
  "    if (!opt) { ok(\"Concentric rings is in the effect list\", false); return; }",
  "    row.value = opt.value; row.dispatchEvent(new Event(\"change\", { bubbles: true }));",
  "    var chev = document.querySelector(\"#panel .lyr button.lyr-pop\");",
  "    if (chev) chev.click();",
  "",
  "    setTimeout(function(){",
  "      // ---- pop two of Polygon's sliders out ----",
  "      // The launcher rows live inside the layer's BOX now (the block moved into the grid),",
  "      // so they are found under #breakout, not #panel.",
  "      var launchers = vis(document.querySelectorAll(\"#breakout .lyr-box .ctl-row .ctl-pop\"));",
  "      ok(\"the layer block offers pop-out launchers\", launchers.length > 2, launchers.length + \" launchers\");",
  "      launchers[0].click();",
  "      launchers[1].click();",
  "      launchers[2].click();",
  "      var boxes = [].slice.call(document.querySelectorAll(\"#breakout .ctl:not(.lyr-box)\"))",
  "                    .filter(function(b){ return b.style.display !== \"none\"; });",
  "      ok(\"three slider boxes opened\", boxes.length === 3, boxes.length + \" visible\");",
  "      // ...and the LAYER box itself is a box in the same grid: dragging, snapping and",
  "      // selecting through the one engine, with the row's +/- as its launcher.",
  "      var lbox = [].slice.call(document.querySelectorAll(\"#breakout .lyr-box\")).filter(function(b){ return b.style.display !== \"none\"; });",
  "      ok(\"the opened layer is a box in the grid\", lbox.length === 1, lbox.length + \" layer boxes\");",
  "      ok(\"...holding the three tabs\", !!lbox[0] && lbox[0].querySelectorAll(\".lyr-tab\").length === 3);",
  "      ok(\"...with the block no longer inside its row\", !document.querySelector(\"#panel .lyr .lyrblock\"));",
  "      var popBtn = document.querySelector(\"#panel .lyr button.lyr-pop\");",
  "      ok(\"the row's launcher reads as open\", !!popBtn && popBtn.textContent === \"−\", popBtn ? popBtn.textContent : \"none\");",
  "      ok(\"...and sits on the RIGHT of the row\", !!popBtn && popBtn.getBoundingClientRect().right > popBtn.parentElement.getBoundingClientRect().right - 24);",
  "      if (boxes.length < 3) { console.log(\"DONE fails=\" + fails); return; }",
  "",
  "      // ---- 1. the free grid ----",
  "      var b0 = boxes[0];",
  "      ok(\"a box is absolutely positioned\", getComputedStyle(b0).position === \"absolute\",",
  "         getComputedStyle(b0).position);",
  "      ok(\"the host does not eat clicks\", getComputedStyle(document.getElementById(\"breakout\")).pointerEvents === \"none\");",
  "      ok(\"but a box does\", getComputedStyle(b0).pointerEvents === \"auto\");",
  "      // The column origin is the PANEL's own right edge and top now, not a hard-coded",
  "      // 298/58 -- that is what \"align the grid to the editor\" means, and asserting the",
  "      // old constants would pass a grid that had quietly stopped tracking the panel.",
  "      var pr = document.getElementById(\"panel\").getBoundingClientRect();",
  "      var GX0 = Math.round(pr.right) + 10, GY0 = Math.round(pr.top), GCW = 254;",
  "      // A layer box heads for the corners: far from the CENTRE of the screen (the",
  "      // picture lives there), on a whole-cell anchor, fully on screen.",
  "      var lr0 = lbox[0].getBoundingClientRect();",
  "      var lcd = Math.hypot(lr0.left + lr0.width / 2 - window.innerWidth / 2,",
  "                           lr0.top + lr0.height / 2 - window.innerHeight / 2);",
  "      ok(\"the first-opened LAYER box lands far from the screen centre\",",
  "         lcd > Math.min(window.innerWidth, window.innerHeight) / 3,",
  "         Math.round(lcd) + \"px from centre (floor \" + Math.round(Math.min(window.innerWidth, window.innerHeight) / 3) + \")\");",
  "      ok(\"...and fully on screen\", lr0.left >= 0 && lr0.top >= 0 &&",
  "         lr0.right <= window.innerWidth && lr0.bottom <= window.innerHeight,",
  "         Math.round(lr0.left) + \",\" + Math.round(lr0.top) + \"..\" + Math.round(lr0.right) + \",\" + Math.round(lr0.bottom));",
  "      function overlaps(a, b){ var ra = a.getBoundingClientRect(), rb = b.getBoundingClientRect();",
  "        return ra.left < rb.right - 0.5 && ra.right > rb.left + 0.5 && ra.top < rb.bottom - 0.5 && ra.bottom > rb.top + 0.5; }",
  "      ok(\"no two visible boxes overlap\",",
  "         !overlaps(b0, boxes[1]) && !overlaps(b0, boxes[2]) && !overlaps(boxes[1], boxes[2]) &&",
  "         !overlaps(lbox[0], b0) && !overlaps(lbox[0], boxes[1]) && !overlaps(lbox[0], boxes[2]));",
  "      // Heights are rounded UP to the quarter-cell grid (the 10px gap included), so",
  "      // stacked boxes leave a uniform gap instead of a different remainder per box.",
  "      var chq = Math.max(48, pr.height / 8) / 4;",
  "      var hrem = (b0.offsetHeight + 10) % chq;",
  "      ok(\"a box's height sits on the quarter-cell grid, gap included\",",
  "         Math.min(hrem, chq - hrem) < 1, b0.offsetHeight + \"px, cell/4 = \" + chq.toFixed(2));",
  "      // A slider popped from an open layer box lands BESIDE it -- adjacent on either side.",
  "      var lbr = lbox[0].getBoundingClientRect(), b0r = b0.getBoundingClientRect();",
  "      ok(\"a popped slider box sits beside its layer box\",",
  "         Math.abs(b0r.left - lbr.right - 10) < 2 || Math.abs(lbr.left - b0r.right - 10) < 2,",
  "         \"box at \" + Math.round(b0r.left) + \", layer \" + Math.round(lbr.left) + \"..\" + Math.round(lbr.right));",
  "",
  "      // Drag box 0 across the middle, to the lower right. It must anchor its RIGHT and",
  "      // BOTTOM edges -- that is the ask: align to the new edge and grow inward.",
  "      var h = b0.querySelector(\".ctl-owner .own-txt\");",
  "      var W = window.innerWidth, H = window.innerHeight;",
  "      var startL = b0.offsetLeft, startT = b0.offsetTop;",
  "      var b1L = boxes[1].offsetLeft, b1T = boxes[1].offsetTop;",
  "      h.dispatchEvent(pt(\"pointerdown\", startL + 20, startT + 6));",
  "      h.dispatchEvent(pt(\"pointermove\", W - 180, H - 220));",
  "      h.dispatchEvent(pt(\"pointerup\", W - 180, H - 220));",
  "      ok(\"a dragged box anchors its RIGHT edge past the middle\",",
  "         b0.style.right !== \"auto\" && b0.style.right !== \"\" && b0.style.left === \"auto\",",
  "         \"left=\" + b0.style.left + \" right=\" + b0.style.right);",
  "      ok(\"...and its BOTTOM edge past the middle\",",
  "         b0.style.bottom !== \"auto\" && b0.style.bottom !== \"\" && b0.style.top === \"auto\",",
  "         \"top=\" + b0.style.top + \" bottom=\" + b0.style.bottom);",
  "      // x only: the corner-seeking layer box may occupy the drop spot, and the overlap",
  "      // nudge then legitimately walks the dropped box up until it is clear.",
  "      ok(\"it really moved to the far half\", b0.offsetLeft > W / 2,",
  "         b0.offsetLeft + \",\" + b0.offsetTop);",
  "      // Snapped to a grid line: the anchored edge sits on a multiple of the cell width.",
  "      // The snap is a QUARTER cell: the anchored corner lands on a multiple of cw/4, ch/4.",
  "      var cw = GCW / 4, ch = Math.max(48, pr.height / 8) / 4;",
  "      // Measured on the RECT, not offsetTop/offsetHeight: those round to whole pixels",
  "      // while the grid (and the min-height sizing) are fractional, and the rounding was",
  "      // enough to read 16.03 quarter-cells on a perfectly-snapped box.",
  "      var b0er = b0.getBoundingClientRect();",
  "      var edgeX = b0er.right - GX0, edgeY = b0er.bottom - GY0;",
  "      // A box dropped near the far edge is CLAMPED to the viewport (right: 0), and the",
  "      // viewport edge is not on the grid -- so the x snap is only asserted when the clamp",
  "      // did not engage. At whole-cell resolution this passed by luck; at quarter-cell it",
  "      // read 20.504 and exposed the clamp. y is unclamped here and must be exact.",
  "      var clampedX = b0.style.right === \"0px\";",
  "      ok(\"the anchored corner sits on a quarter-cell line measured from the panel\",",
  "         (clampedX || Math.abs(edgeX / cw - Math.round(edgeX / cw)) < 0.02) &&",
  "         Math.abs(edgeY / ch - Math.round(edgeY / ch)) < 0.02,",
  "         (edgeX / cw).toFixed(3) + (clampedX ? \" (x clamped to the viewport edge)\" : \"\") + \" / \" + (edgeY / ch).toFixed(3) + \" quarter-cells\");",
  "      // ...and it is genuinely finer than whole cells: drop a box a third of a cell in",
  "      // from the panel and it must NOT be pulled back to the panel edge.",
  "      var third = Math.round(GCW / 3);",
  // DROPPED INTO FREE SPACE, low-left, and that matters. A drop now resolves through",
  // nearestFree, which searches BOTH axes for the closest clear on-screen spot -- so a drop",
  // onto an occupied cell (GY0 + 6 is inside layer 1's box) legitimately moves in x as well",
  // as y, and this assertion would be measuring the de-overlap search rather than the snap.",
  // The old one-directional nudge only ever moved in y, which is why it used to pass here.",
  "      var freeY = Math.round(H * 0.78);",
  "      h.dispatchEvent(pt(\"pointerdown\", b0.offsetLeft + 20, b0.offsetTop + 6));",
  "      h.dispatchEvent(pt(\"pointermove\", GX0 + third + 20, freeY));",
  "      h.dispatchEvent(pt(\"pointerup\", GX0 + third + 20, freeY));",
  "      var offX = b0.offsetLeft - GX0;",
  "      ok(\"a box dropped a third of a cell in snaps to the nearest QUARTER, not the cell edge\",",
  "         offX > 0 && Math.abs(offX - Math.round(GCW / 4)) < 2, offX + \"px in, quarter = \" + (GCW / 4).toFixed(1));",
  "      // put it back to the lower-right for the assertions that follow",
  "      h.dispatchEvent(pt(\"pointerdown\", b0.offsetLeft + 20, b0.offsetTop + 6));",
  "      h.dispatchEvent(pt(\"pointermove\", W - 180, H - 220));",
  "      h.dispatchEvent(pt(\"pointerup\", W - 180, H - 220));",
  "      // The other slider boxes are ANCHORED beside their layer box, so dragging b0 away",
  "      // must not move them -- a box you placed (or the engine placed for you) stays put.",
  "      ok(\"the anchored neighbours stay put when a box is dragged away\",",
  "         boxes[1].offsetLeft === b1L && boxes[1].offsetTop === b1T,",
  "         boxes[1].offsetLeft + \",\" + boxes[1].offsetTop + \" was \" + b1L + \",\" + b1T);",
  "      // Drag it back across the middle: it has to flip to the LEFT edge, not keep a stale",
  "      // right anchor -- that flip is the behaviour the whole snap exists for.",
  "      h.dispatchEvent(pt(\"pointerdown\", b0.offsetLeft + 20, b0.offsetTop + 6));",
  "      h.dispatchEvent(pt(\"pointermove\", 120, 120));",
  "      h.dispatchEvent(pt(\"pointerup\", 120, 120));",
  "      ok(\"dragging back across the middle flips it to the LEFT edge\",",
  "         b0.style.left !== \"auto\" && b0.style.right === \"auto\",",
  "         \"left=\" + b0.style.left + \" right=\" + b0.style.right);",
  "      // Double-click the title returns it to the flow column. The flow steers around",
  "      // anchored boxes now, so \"the column\" means: on a whole-cell column line,",
  "      // overlapping nothing -- not necessarily column 0, which the layer box may fill.",
  "      h.dispatchEvent(new MouseEvent(\"dblclick\", { bubbles: true }));",
  "      var colOff = (b0.offsetLeft - GX0) % GCW;",
  "      ok(\"double-clicking the title puts it back in a flow column\",",
  "         colOff === 0, b0.offsetLeft + \" (offset \" + colOff + \")\");",
  "      ok(\"...without burying another box\",",
  "         !overlaps(b0, lbox[0]) && !overlaps(b0, boxes[1]) && !overlaps(b0, boxes[2]));",
  "",
  "      // ---- 1b. the grid is VISIBLE while dragging, and matches the maths ----",
  "      var grid = document.getElementById(\"brkgrid\");",
  "      ok(\"the snap grid element exists\", !!grid);",
  "      ok(\"it is invisible at rest\", getComputedStyle(grid).opacity === \"0\",",
  "         getComputedStyle(grid).opacity);",
  "      // KILL THE TRANSITION FIRST and measure the RULE, not the animation. #brkgrid fades",
  "      // on a CSS transition, which runs on REAL time -- headless virtual time skips past",
  "      // it, so a timeout of 400 virtual ms reads back somewhere between 0 and 0.03",
  "      // depending on how much real time the run happened to spend. Measured both ways",
  "      // before this: as an end-value assertion it fails against correct code, and as a",
  "      // greater-than-zero one it is simply flaky. With the transition off the class",
  "      // toggle is instant and the check is exact.",
  "      grid.style.transition = \"none\";",
  "      h.dispatchEvent(pt(\"pointerdown\", b0.offsetLeft + 20, b0.offsetTop + 6));",
  "      ok(\"a drag arms it\", document.body.classList.contains(\"brk-gridding\"));",
  "      var gs = getComputedStyle(grid);",
  "      ok(\"...and the rule takes it to full opacity\", gs.opacity === \"1\", gs.opacity);",
  "      var gr = grid.getBoundingClientRect();",
  "      ok(\"the drawn grid starts where the maths says\",",
  "         Math.abs(gr.left - GX0) < 1 && Math.abs(gr.top - GY0) < 1, gr.left + \",\" + gr.top);",
  "      // Four background layers: the fine mesh at a quarter cell, the strong lines at one",
  "      // box width. Both sizes must be present, fine first (on top).",
  "      var sizes = gs.backgroundSize.split(\",\").map(function(x){ return x.trim(); });",
  "      ok(\"the drawn grid has a fine mesh AND strong whole-cell lines\", sizes.length === 4 &&",
  "         sizes[0].indexOf((GCW / 4) + \"px\") === 0 && sizes[2].indexOf(GCW + \"px\") === 0, gs.backgroundSize);",
  "      var imgs = gs.backgroundImage;",
  "      ok(\"...and the whole-cell lines are the stronger ones\",",
  "         imgs.indexOf(\"0.16\") >= 0 && imgs.indexOf(\"0.62\") >= 0 && imgs.indexOf(\"0.16\") < imgs.indexOf(\"0.62\"),",
  "         \"fine alpha .16 listed before strong alpha .62\");",
  "      h.dispatchEvent(pt(\"pointerup\", b0.offsetLeft + 20, b0.offsetTop + 6));",
  "      ok(\"releasing disarms it again\", !document.body.classList.contains(\"brk-gridding\"));",
  "      ok(\"...and hides it\", getComputedStyle(grid).opacity === \"0\", getComputedStyle(grid).opacity);",
  "      grid.style.transition = \"\";",
  "      h.dispatchEvent(new MouseEvent(\"dblclick\", { bubbles: true }));",
  "",
  "      // ---- 2. the shape thumbnail ----",
  "      var cv = b0.querySelector(\"canvas.shape-prev\");",
  "      ok(\"a shape group's box carries a thumbnail\", !!cv);",
  "      if (cv) {",
  "        var g = cv.getContext(\"2d\");",
  "        function ink(){",
  "          var d = g.getImageData(0, 0, cv.width, cv.height).data, n = 0;",
  "          for (var i = 3; i < d.length; i += 4) if (d[i] > 8) n++;",
  "          return n;",
  "        }",
  "        // A HASH of the pixels, not a count of them. A 5-gon and a 12-gon outline have",
  "        // nearly the same perimeter, so counting ink moved by 6 pixels out of 1650 and the",
  "        // check would have passed against a thumbnail that never redrew at all.",
  "        function sig(){",
  "          var d = g.getImageData(0, 0, cv.width, cv.height).data, hsh = 2166136261;",
  "          for (var i = 3; i < d.length; i += 4) { hsh ^= d[i]; hsh = Math.imul(hsh, 16777619); }",
  "          return hsh >>> 0;",
  "        }",
  "        ok(\"it has drawn something\", ink() > 40, ink() + \" inked pixels\");",
  "        var sides = [].slice.call(document.querySelectorAll(\"#breakout [data-k]\"))",
  "                      .filter(function(e){ return e.getAttribute(\"data-k\") === \"cosides-lo\"; })[0];",
  "        if (!sides) { ok(\"the Polygon Sides slider is in a box\", false); }",
  "        else {",
  "          var was = sig();",
  "          sides.value = \"12\"; sides.dispatchEvent(new Event(\"input\", { bubbles: true }));",
  "          var now = sig();",
  "          ok(\"the thumbnail follows its group's sliders\", now !== was, was + \" -> \" + now);",
  "          // ...and it is EVERY box of the group, not just the one holding that slider.",
  "          var others = boxes.filter(function(b){ return b !== b0 && b.querySelector(\"canvas.shape-prev\"); });",
  "          ok(\"every box in the group shows the same figure\", others.length > 0,",
  "             others.length + \" sibling thumbnails\");",
  "        }",
  "      }",
  "",
  "      // ---- 3. the trigger fold ----",
  "      // NOT b0: the first Polygon slider is Sides, which is a `single` control, and single",
  "      // controls suppress their triggers by design (wireRange: beat !== false && !single).",
  "      // Asserting the fold on a box that correctly has no chips is a check of nothing.",
  "      var bt = boxes.filter(function(b){ return b.querySelector(\".trig-chev\"); })[0];",
  "      ok(\"a beat-armable box carries a fold chevron on its Triggers heading\", !!bt);",
  "      ok(\"a single control still has NO trigger section\", !b0.querySelector(\".trig-chev\"),",
  "         \"Sides is single\");",
  "      var tchev = bt && bt.querySelector(\".trig-chev\");",
  "      var chips = bt && bt.querySelector(\".bandchips\");",
  "      ok(\"the chips start visible\", !!chips && chips.style.display !== \"none\");",
  "      if (tchev && chips) {",
  "        // ARM a band first: the point of the feature is folding an ARMED trigger away.",
  "        var lband = chips.querySelector(\"button\");",
  "        lband.click();",
  "        var body = bt.querySelector(\".trig-body\");",
  "        ok(\"arming a band opens the trigger body\", !!body && body.style.display !== \"none\",",
  "           body ? (body.style.display || \"shown\") : \"no body\");",
  "        tchev.click();",
  "        ok(\"the chevron hides the chips even though a band is armed\",",
  "           chips.style.display === \"none\", chips.style.display || \"shown\");",
  "        ok(\"...and the trigger body with them\", !!body && body.style.display === \"none\",",
  "           body ? (body.style.display || \"shown\") : \"no body\");",
  "        ok(\"...but the band is still armed\", lband.classList.contains(\"on\"));",
  "        tchev.click();",
  "        ok(\"clicking again brings the armed trigger back\",",
  "           chips.style.display !== \"none\" && !!body && body.style.display !== \"none\",",
  "           \"chips=\" + (chips.style.display || \"shown\") + \" body=\" + (body.style.display || \"shown\"));",
  "        // THE PULSE PLOT: value against time after a beat, drawn from the animation's",
  "        // own formula. Hash the pixels -- a count moves by a handful between two curves",
  "        // with the same endpoints, which is the thumbnail lesson again.",
  "        var pp = bt.querySelector(\"canvas.pulse-plot\");",
  "        ok(\"the trigger section carries a pulse plot\", !!pp);",
  "        if (pp) {",
  "          var pg = pp.getContext(\"2d\");",
  "          function psig(){ var d = pg.getImageData(0, 0, pp.width, pp.height).data, h = 2166136261; for (var i = 3; i < d.length; i += 4) { h ^= d[i]; h = Math.imul(h, 16777619); } return h >>> 0; }",
  "          function pink(){ var d = pg.getImageData(0, 0, pp.width, pp.height).data, n = 0; for (var i = 3; i < d.length; i += 4) if (d[i] > 8) n++; return n; }",
  "          // The CURVE's vertical extent: rows holding a strongly-orange pixel (the curve is",
  "          // #ff9a3c at full alpha; the band lines and beat marker are faint). A pinned",
  "          // slider's curve is one flat row; a live one spans most of the plot. Counting all",
  "          // ink cannot tell them apart -- the furniture is ~500px either way.",
  "          function curveRows(){ var d = pg.getImageData(0, 0, pp.width, pp.height).data, rows = {}; for (var y = 0; y < pp.height; y++) for (var x = 0; x < pp.width; x++) { var i = (y * pp.width + x) * 4; if (d[i+3] > 200 && d[i] > 200 && d[i+1] > 120 && d[i+1] < 190) { rows[y] = 1; break; } } return Object.keys(rows).length; }",
  "          ok(\"...and it has drawn a curve\", pink() > 150, pink() + \" inked px\");",
  "          var sel = bt.querySelector(\"select.pulsesel\");",
  "          var s0 = psig();",
  "          sel.value = \"bounce\"; sel.dispatchEvent(new Event(\"change\", { bubbles: true }));",
  "          var s1 = psig();",
  "          ok(\"picking another shape redraws it\", s1 !== s0, s0 + \" -> \" + s1);",
  "          // Duration does NOT change the picture, and that is the point: the x axis is",
  "          // scaled to the pulse length, so the plot shows the SHAPE of the fall whatever",
  "          // its length. A first draft asserted the opposite and failed on correct code.",
  "          var dur = bt.querySelector(\".plen input[type=range]\");",
  "          dur.value = \"0.9\"; dur.dispatchEvent(new Event(\"input\", { bubbles: true }));",
  "          ok(\"the plot is duration-invariant (x scaled to the pulse length)\", psig() === s1);",
  "          // ...but the slider's own BAND is the y axis, so a pinned slider draws flat.",
  "          // The thumbs are the two range inputs INSIDE .dual (the Duration slider is a",
  "          // range input too, further down the box -- a bare querySelector finds whichever",
  "          // comes first).",
  "          var th = bt.querySelectorAll(\".dual input[type=range]\");",
  "          var lo2 = th[0], hi2 = th[1];",
  "          if (lo2 && hi2) {",
  "            // Every shipped slider is PINNED (lo == hi), so the plot is honestly flat until",
  "            // the band is opened -- a first draft of this check asserted a curve on the",
  "            // default and learned that. Spread the thumbs first, then pin them again.",
  "            hi2.value = hi2.max; hi2.dispatchEvent(new Event(\"input\", { bubbles: true }));",
  "            var before = curveRows();",
  "            ok(\"a spread band draws a curve that spans the plot\", before > 20, before + \" rows (lo=\" + lo2.value + \" hi=\" + hi2.value + \")\");",
  "            hi2.value = lo2.value; hi2.dispatchEvent(new Event(\"input\", { bubbles: true }));",
  "            ok(\"a pinned slider plots a flat line -- a trigger on it does nothing\", curveRows() <= 3,",
  "               before + \" -> \" + curveRows() + \" rows (lo=\" + lo2.value + \" hi=\" + hi2.value + \")\");",
  "          } else ok(\"found the two thumbs\", false, th.length + \" range inputs in .dual\");",
  "        }",
  "      }",
  "",
  "",
  "      // ---- 4. a floating tool panel drags onto the same grid ----",
  "      var opener = document.getElementById(\"transpick-open\");",
  "      ok(\"the transitions picker has an opener\", !!opener);",
  "      if (opener) {",
  "        opener.click();                    // built on OPEN -- un-hiding it proves nothing",
  "        var dbox = document.querySelector(\"#transpickdlg .flt-box\");",
  "        var dh2 = dbox && dbox.querySelector(\"h2\");",
  "        ok(\"...and a title bar to grab\", !!dh2);",
  "        if (dh2) {",
  "          ok(\"the title bar advertises itself\", getComputedStyle(dh2).cursor === \"grab\",",
  "             getComputedStyle(dh2).cursor);",
  "          var d0 = dbox.getBoundingClientRect();",
  "          dh2.dispatchEvent(pt(\"pointerdown\", d0.left + 40, d0.top + 8));",
  "          ok(\"dragging a panel arms the grid too\", document.body.classList.contains(\"brk-gridding\"));",
  "          dh2.dispatchEvent(pt(\"pointermove\", W - 240, 300));",
  "          dh2.dispatchEvent(pt(\"pointerup\", W - 240, 300));",
  "          ok(\"the panel was converted from relative to absolute so it can be placed\",",
  "             getComputedStyle(dbox).position === \"absolute\", getComputedStyle(dbox).position);",
  "          ok(\"...and anchored to the near edge past the middle\",",
  "             dbox.style.right !== \"auto\" && dbox.style.right !== \"\",",
  "             \"left=\" + dbox.style.left + \" right=\" + dbox.style.right);",
  "          var d1 = dbox.getBoundingClientRect();",
  "          ok(\"it really moved\", d1.left > W / 2, String(Math.round(d1.left)));",
  "          dh2.dispatchEvent(new MouseEvent(\"dblclick\", { bubbles: true }));",
  "          ok(\"double-click hands it back to the CSS dock\",",
  "             dbox.style.left === \"\" && dbox.style.position === \"\",",
  "             \"left=\" + dbox.style.left + \" pos=\" + dbox.style.position);",
  "        }",
  "      }",
  "",
  "      ok(\"no console errors through all of it\", window.__errs === 0, window.__errs + \" errors\");",
  "      console.log(\"DONE fails=\" + fails);",
  "    }, 1200);",
  "  }, 1800);",
  "})();",
].join(NL);

let s = app.replace("<head>", "<head>" + NL + "<script>" + SEED + "<" + "/script>");
s = s.replace("</body>", "<script>" + ASSERT + "<" + "/script>" + NL + "</body>");
if (s === app) throw new Error("injection failed");
const f = path.join(outDir, "breakout.html");
fs.writeFileSync(f, s);
console.log("wrote " + f);

const abs = path.resolve(outDir).split(path.sep).join("/");
console.log(NL + "run with:");
console.log("  msedge --headless=new --disable-extensions --enable-logging=stderr --v=0"
  + " --window-size=1600,1000 --virtual-time-budget=60000"
  + " --user-data-dir=\"" + abs + "/ud-breakout\""
  + " \"file:///" + abs + "/breakout.html\" 2>&1 | grep -oE " + Q + "\"(PASS|FAIL|DONE)[^\"]*\"" + Q);
